batch_size: 32
iters: 80000

train_dataset:
  type: COCODataset
  image_root: data/UWMGI/images/
  json_file: data/UWMGI/annotations/train.json
  num_classes: 3
  use_multilabel: True
  transforms:
    - type: Resize
      target_size: [224, 224]
      interp: NEAREST
    - type: RandomHorizontalFlip
    - type: RandomAffine
      max_rotation: 10
      min_scale_factor: 0.95
      max_scale_factor: 1.05
      size: [224, 224]
      translation_offset: 14
    - type: RandomDistort
      brightness_range: 0.05
      contrast_range: 0.05
      saturation_range: 0.05
    - type: Normalize
      mean: [0.0, 0.0, 0.0]
      std: [1.0, 1.0, 1.0]
  mode: train

val_dataset:
  type: COCODataset
  image_root: data/UWMGI/images/
  json_file: data/UWMGI/annotations/val.json
  num_classes: 3
  use_multilabel: True
  transforms:
    - type: Resize
      target_size: [224, 224]
      interp: NEAREST
    - type: Normalize
      mean: [0.0, 0.0, 0.0]
      std: [1.0, 1.0, 1.0]
  mode: val

optimizer:
  type: SGD
  momentum: 0.9
  weight_decay: 4.0e-5

lr_scheduler:
  type: PolynomialDecay
  learning_rate: 0.01
  end_lr: 0
  power: 0.9

loss:
  types:
    - type: BCELoss
  coef: [1]
